version: '2'
services:
  shellbox:
    restart: always
    build: ./shellbox
    cap_add: 
      - SYS_ADMIN
    expose:
      - "22/tcp"
    links:
      - "db:db"
    depends_on:
      - db
  signup:
    restart: always
    build: ./signup
    environment:
      - PORT=22
    cap_add: 
      - NET_BIND_SERVICE
    expose:
      - "22/tcp"
  db:
    restart: always
    image: postgres:9.5
    expose:
      - "5432/tcp"
